config/routes.rb
PET::Application.routes.draw do

  get  "projects/index"
  get  'projects'                         => 'projects#index',                  as: 'projects_index'
  get  'projects/new'                     => 'projects#new',                    as: 'new_project'
  get  'projects/:id'                     => 'projects#show',                   as: 'project'
  post 'projects/create'                  => 'projects#create',                 as: 'projects'

  get 'project_phases/:id'                => 'project_phases#show',             as: 'project_phase'

  get 'project_phase_deliverable/new'     => 'project_phase_deliverable#new',   as: 'new_project_phase_deliverable'
  get 'project_phase_deliverable/:id'     => 'project_phase_deliverable#show',  as: 'project_phase_deliverable'
  post 'project_phase_deliverable/create' => 'project_phase_deliverable#create',as: 'create_project_phase_deliverable'

   root :to => 'projects#index'

end

app/models/project_phase_deliverable.rb
class ProjectPhaseDeliverable < ActiveRecord::Base
  # To change this template use File | Settings | File Templates.
  attr_accessible :project_phase_id, :name, :description, :uom_id, :size, :rate, :complexity_id, :deliverable_type_id, :effort

  belongs_to :project_phase
  belongs_to :deliverable_type
  belongs_to :uom

  validates :project_phase_id,    presence:true
  validates :name,                presence:true
  validates :uom_id,              presence:true
  validates :size,                presence:true
  validates :rate,                presence:true
  validates :complexity_id,       presence:true
  validates :deliverable_type_id, presence:true
  validates :effort,              presence:true

  @@complexities = {1 => "Simple", 2 => "Medium", 3 => "Complex"}

  # add some dummy data for testing
  #@@deliverable_types = {1 => "Type 1", 2 => "Type 2", 3 => "Type 3"}
  @@units_of_measurement = {1 => "Words", 2 => "Pages", 3 => "Story Points", 4 => "Lines"}

  def self.complexities
    @@complexities
  end

  def complexity_string
    @@complexities[complexity_id]
  end


  #def self.deliverable_types
  #  @@deliverable_types
  #end

  #def deliverable_type_string
  #  @@deliverable_types[deliverable_type_id]
  #end


  #def self.units_of_measurement
  #  @@units_of_measurement
  #end

  def uom_string
    @@units_of_measurement[uom_id]
  end

end

app/controllers/project_phase_deliverable_controller.rb
class ProjectPhaseDeliverableController < ApplicationController

  # TODO: We should really refactor how we're calling globally used variables/resources

  def show
    @deliverable          = ProjectPhaseDeliverable.find(params[:id])
    @project_phase_id     = @deliverable.project_phase_id
    getDeliverableTypes()
    @uoms = Uom.getAllForSelect
  end

  def new
    @project_phase_id     = params[:project_phase_id]

    if @project_phase_id.nil? || @project_phase_id.empty?
      flash[:alert] = "Please specify project phase id in order to create new deliverable."
      redirect_to '/projects'
    else
      @deliverable          = ProjectPhaseDeliverable.new
      getDeliverableTypes()
      @uoms = Uom.getAllForSelect
    end
  end

  def create

    @project_phase_id     = params[:project_phase_deliverable][:project_phase_id]

    if @project_phase_id.nil? || @project_phase_id.empty?
      flash[:alert] = "Please specify project phase id in order to create new deliverable."
      redirect_to '/projects'
    else
      @deliverable = ProjectPhaseDeliverable.new(
        project_phase_id:  @project_phase_id,
        name: params[:project_phase_deliverable][:name],
        description: params[:project_phase_deliverable][:description],
        uom_id: params[:project_phase_deliverable][:uom_id],
        size: params[:project_phase_deliverable][:size],
        rate: params[:project_phase_deliverable][:rate],
        complexity_id: params[:project_phase_deliverable][:complexity_id],
        deliverable_type_id: params[:project_phase_deliverable][:deliverable_type_id],
        effort:  params[:project_phase_deliverable][:effort]
      )

      if @deliverable && @deliverable.save
        flash[:success] = "New deliverable was successfully created"
        redirect_to '/project_phases/' + @deliverable.project_phase_id.to_s
      else
        flash[:alert] = "Please fix the following errors."
        getDeliverableTypes()
        @uoms = Uom.getAllForSelect
        render :new
      end
    end
  end

  # Get deliverable types by lifecycle phase ID
  # Helper method, not intended to be called from outside
  # Populates @deliverableTypes with deliverable types for lifecycle phase
  # Populates @deliverableTypesArray with deliverable type names keyed by deliverable type IDs
  def getDeliverableTypes
    @projectPhase = ProjectPhase.find(@project_phase_id)
    @deliverableTypes = DeliverableType.find_all_by_lifecycle_phase_id(@projectPhase.lifecycle_phase_id)
    @deliverableTypesArray = []
    @deliverableTypes.each do |type|
      @deliverableTypesArray.append([type.name,type.id])
    end
  end
end

app/views/project_phase_deliverable/_form.html.erb
<%
   #TODO: Populate this data from the controller
   @types = {"1" => "1",'2' => '2', '3' => '3'}
%>

<script type="text/javascript">
    var types = <%= ActiveSupport::JSON.encode(@types).html_safe %>;
</script>

<% if @deliverable.errors.any? %>
    <% @deliverable.errors.full_messages.each do |msg| %>
        <small class="error"><%= msg %></small>
    <% end %>
<% end %>
<div class="row">
  <div class="large-12 columns">
    <%= f.label :name, 'Name <small>required</small>'.html_safe, class: "project_phase_deliverable_field_label" %>
    <%= f.text_field :name %>
  </div>
</div>
<div class="row">
  <div class="large-12 columns">
    <%= f.label :description, 'Description'.html_safe, class: "project_phase_deliverable_field_label" %>
    <%= f.text_area :description %>
  </div>
</div>
<div class="row">
  <div class="large-12 columns">
    <%= f.label :deliverable_type_id, 'Deliverable Type <small>required</small>'.html_safe, class: "project_phase_deliverable_field_label" %>
    <%= f.select :deliverable_type_id, @deliverableTypesArray %>
  </div>
</div>
<div class="row">
  <div class="large-12 columns">
    <%= f.label :uom_id, 'Unit of Measurement <small>required</small>'.html_safe, class: "project_phase_deliverable_field_label" %>
    <%= f.select :uom_id, @uoms %>
  </div>
</div>
<div class="row">
  <div class="large-12 columns">
    <%= f.label :complexity_id, 'Complexity <small>required</small>'.html_safe, class: "project_phase_deliverable_field_label" %>
    <%= f.select :complexity_id, ProjectPhaseDeliverable.complexities.collect{ |index, value| [value, index] } %>
  </div>
</div>
<div class="row">
  <div class="large-12 columns">
    <%= f.label :size, 'Size <small>required</small>'.html_safe, class: "project_phase_deliverable_field_label" %>
    <%= f.text_field :size %>
  </div>
</div>
<div class="row">
  <div class="large-12 columns">
    <%= f.label :rate, 'Rate <small>required</small>'.html_safe, class: "project_phase_deliverable_field_label" %>
    <%= f.text_field :rate %>
  </div>
</div>
<div class="row">
  <div class="large-12 columns">
    <%= f.label :effort, 'Effort <small>required</small>'.html_safe, class: "project_phase_deliverable_field_label" %>
    <%= f.text_field :effort %>
  </div>
</div>

<%= f.hidden_field :project_phase_id, :value => @project_phase_id %>

app/views/project_phase_deliverable/new.html.erb
<% provide(:title, "Create New Deliverable") %>

<h3 id="page_header">Create New Deliverable</h3>

<fieldset>
  <%= form_for(@deliverable, :url => create_project_phase_deliverable_path, :method => :post) do |f| %>

    <%= render 'form', :f => f %>


    <!-- Cancel and Create buttons -->
    <div class="row">
      <div class="large-3 large-offset-9 columns">
        <input class="tiny button" type="submit" name="Submit" value="Create">
        <a class="tiny button" href="/project_phases/<%= @project_phase_id %>">Cancel</a>
      </div>
    </div>

    <!--< % if @new_project.errors.any? %>-->
        <!--< % @new_project.errors.full_messages.each do |msg| %>-->
            <!--<small class="error">< %= msg %></small>-->
        <!--< % end %>-->
    <!--< % end %>-->
  <% end %>
</fieldset>

app/views/project_phase_deliverable/show.html.erb
<% provide(:title, "Edit Deliverable") %>

<h3 id="page_header">Edit <%= @deliverable.name %></h3>

<fieldset>
  <%= form_for @deliverable do |f| %>
    <%= render "form", :f => f %>

    <!-- Cancel and Create buttons -->
    <div class="row">
      <div class="large-3 large-offset-9 columns">
        <input class="tiny button" type="submit" name="Submit" value="Edit">
        <a class="tiny button" href="/project_phases/<%= @project_phase_id %>">Cancel</a>
      </div>
    </div>

  <% end %>
</fieldset>