config/routes.rb
PET::Application.routes.draw do

  get  "projects/index"
  get  'projects'                         => 'projects#index',                  as: 'projects_index'
  get  'projects/new'                     => 'projects#new',                    as: 'new_project'
  get  'projects/:id'                     => 'projects#show',                   as: 'project'
  post 'projects/create'                  => 'projects#create',                 as: 'projects'

  get 'project_phases/:id'                => 'project_phases#show',             as: 'project_phase'

  get 'project_phase_deliverable/new'     => 'project_phase_deliverable#new',   as: 'new_project_phase_deliverable'
  get 'project_phase_deliverable/:id'     => 'project_phase_deliverable#show',  as: 'project_phase_deliverable'
  post 'project_phase_deliverable/create' => 'project_phase_deliverable#create',as: 'create_project_phase_deliverable'

   root :to => 'projects#index'

end

app/models/project.rb
# == project.rb
# A project is a collaborative product which consists of a series of plans
# that user defines to carry out the plans.
# This file contains the details of a project that user creates.
#
# It also includes the Project model definition with associations
# to different models (ProjectPhase and Lifecycle).
# One project is composed of the name of a project, the description,
# and the ID of a specific lifecycle that the project uses.
# === Fields:
# * Name: unique character string that identifies the Lifecycle (required)
# * Description: character string that explains the Lifecycle (optional)
# * lifecycle_id: a numeric ID used as a foreign key to locate a specific lifecycle (required)

class Project < ActiveRecord::Base
  # A project has many project phases within the project.
  has_many        :project_phases

  # A project belongs to the lifecycle.
  belongs_to      :lifecycle

  # A project can have a name, a description, and a lifecycle ID
  # used as a foreign key to refer to the Lifecycle model.
  attr_accessible :name, :description, :lifecycle_id
  # A project name is required to create a project.
  validates :name, presence:true
  # A project name must be unique across the whole database.
  validates :name, uniqueness:true

  # A project lifecycle_id is required to create a project.
  validates :lifecycle_id, presence:true

  after_create :create_project_phases

  def create_project_phases
    lifecyclePhases = LifecyclePhase.find_all_by_lifecycle_id(self.lifecycle_id)
    lifecyclePhases.each do |lifecyclePhase|
      ProjectPhase.create(project_id: self.id, lifecycle_phase_id: lifecyclePhase.id)
    end
  end
end

app/controllers/projects_controller.rb
# * *Filename*    : projects_controller.rb
# * *Date*        : 09-30-2013
# * *Team*        : Rails Byters
# * *Description* : This controller provides a REST api to query, create, and modify projects in PET
#
class ProjectsController < ApplicationController

  # This function joins project table with lifecycle table and returns a list of all projects
  # with matching lifecycle information
  # * *Http*  :
  #   - <tt>GET /projects</tt>
  def index
    @projects = Project.joins(:lifecycle)
  end

  # This function returns a project with a given id and its matching lifecycle information
  # * *Http*  :
  #   - <tt>GET /projects/1</tt>
  def show
    @project = Project.joins(:lifecycle, {
        :project_phases => [:lifecycle_phase]
    }).find(params[:id])
  end

  # This function accept a json string as parameters for a new project and attempt to create
  # a new project in the database.
  # * *Args*    :
  #   - <tt>name:string</tt> - the name of the project
  #   - <tt>description:string</tt> - the description string of the project
  #   - <tt>lifecycle_id:number</tt> - the id of the project lifecycle
  # * *Returns* :
  #   - if successful: redirects to project overview page and flash success message
  #   - if unsuccessful: redirects to new project form and flash error message
  # * *Http*    :
  #   - <tt>POST /projects</tt>
  def create
    @new_project = Project.new(name: params[:project][:name],
                               description: params[:project][:description],
                               lifecycle_id: params[:project][:lifecycle_id])

    if @new_project && @new_project.save
      flash[:success] = "Project was successfully created"
      redirect_to @new_project
    else
      flash.now[:alert] = "Please fix the following errors."

      # /projects/new needs @lifecycles to render
      @lifecycles = Lifecycle.all
      render :new
    end
  end

  # This function gets a list of all lifecycles in lifecycle table and renders the new project html form
  # * *Http*  :
  #   - <tt>GET /projects/new</tt>
  def new
    @new_project = Project.new
    @lifecycles  = Lifecycle.all
  end

end

app/views/projects/index.html.erb
<% provide(:title, "Projects") %>
Bla bla bla
<div class="row">
  <div class="large-6 columns">
    <h3>Existing Projects</h3>
  </div>

  <div class="large-4 large-offset-2 columns">
    <%= link_to "Create New Project", new_project_path, class: "button expand" %>
  </div>
</div>

<table id="projects-table">
  <thead>
      <tr>
        <th scope="col">Name </th>
        <th scope="col">Description</th>
        <th scope="col">Lifecycle</th>
      </tr>
  </thead>

  <tbody>
    <% @projects.each_with_index do |project, index| %>
      <tr id="row_<%= index %>">
        <td class="name">
          <%= link_to project.name, project_path(:id => index + 1) %>
        </td>
        <td class="description"><%= project.description %></td>
        <td class="lifecycle"><%= project.lifecycle.name %></td>
      </tr>
<% end %>
  </tbody>
</table>

app/views/projects/new.html.erb
<% provide(:title, "Create New Project") %>

<h3 id="page_header">Create New Project</h3>

<fieldset>
  <% if @new_project.errors.any? %>
      <% @new_project.errors.full_messages.each do |msg| %>
          <small class="error"><%= msg %></small>
      <% end %>
  <% end %>
  <%= form_for @new_project do |f| %>
    <div class="row">
      <div class="large-12 columns">
        <%= f.label :name, 'Name <small>required</small>'.html_safe, class: "project_field_label" %>
        <%= f.text_field :name %>
      </div>
    </div>
    <div class="row">
      <div class="large-12 columns">
        <%= f.label :description, class: "project_field_label" %>
        <%= f.text_area :description %>
      </div>
    </div>
    <div class="row">
      <div class="large-3 columns">
        <%= f.label :lifecycle_id, class: "project_field_label" %>
        <%= f.select :lifecycle_id, @lifecycles.collect{ |l| [l.name, l.id] } %>
      </div>
    </div>
    <div class="row">
      <div class="large-3 large-offset-9 columns">
        <input class="tiny button" type="submit" name="Submit" value="Create">
        <a class="tiny button" href="/projects">Cancel</a>
      </div>
    </div>
  <% end %>
</fieldset>

app/views/projects/show.html.erb
<% provide(:title, "Project Overview") %>

<h3 id="page_header"><%= @project.name %> Overview</h3>

<fieldset>
  <form>
    <div class="row">
      <div class="large-12 columns">
        <label class="project_field_label">Name</label>
        <input type="text" id="name" value="<%= @project.name %>">
        </input>
      </div>
    </div>

    <div class="row">
      <div class="large-12 columns">
        <label class="project_field_label">Description</label>
        <textarea type="text" id="description"><%= @project.description %></textarea>
      </div>
    </div>

    <div class="row">
      <div class="large-6 columns">
        <label class="project_field_label">Lifecycle</label>
        <input type="text" id="lifecycle" disabled="disabled" value="<%= @project.lifecycle.name %>"> </input>
      </div>

      <div class="large-6 columns">
        <label class="project_field_label">Total Estimation</label>
        <input type="text" id="total_estimation" value="" disabled="disabled" />
      </div>
    </div>

    <div class="row">
      <div class="large-12 columns">
          <table id="phase_table">
            <thead>
            <tr>
              <th scope="col"> Project Phases </th>
              <th scope="col"> Estimates </th>
            </tr>
            </thead>

            <tbody>
            <% @project.project_phases.each_with_index do |project_phase, index| %>
                <tr id="row_<%= index %>">
                  <td class="name"> <%= link_to project_phase.lifecycle_phase.name, project_phase_path(:id => project_phase.id) %> </td>
                  <td class="estimates"> 100 </td>
                </tr>
            <% end %>
            </tbody>
          </table>
      </div>
    </div>

    <div class="row">
      <div class="large-4 large-offset-8 columns">
        <a href="#" class="tiny button" name="Submit" value="Submit">Save</a>
        <a href="/projects" class="tiny button" name="Back" value="Back">Back</a>
        <a href="#" class="tiny button" name="Delete" value="Delete">Delete</a>
      </div>
    </div>
  </form>
</fieldset>