config/routes.rb
PET::Application.routes.draw do

  get  "projects/index"
  get  'projects'                         => 'projects#index',                  as: 'projects_index'
  get  'projects/new'                     => 'projects#new',                    as: 'new_project'
  get  'projects/:id'                     => 'projects#show',                   as: 'project'
  post 'projects/create'                  => 'projects#create',                 as: 'projects'

  get 'project_phases/:id'                => 'project_phases#show',             as: 'project_phase'

  get 'project_phase_deliverable/new'     => 'project_phase_deliverable#new',   as: 'new_project_phase_deliverable'
  get 'project_phase_deliverable/:id'     => 'project_phase_deliverable#show',  as: 'project_phase_deliverable'
  post 'project_phase_deliverable/create' => 'project_phase_deliverable#create',as: 'create_project_phase_deliverable'

   root :to => 'projects#index'

end

app/controllers/project_phases_controller.rb
# * *Filename*    : project_phases_controller.rb
# * *Date*        : 09-30-2013
# * *Team*        : Rails Byters
# * *Description* : This controller provides an api to query and create project phases in PET
#
class ProjectPhasesController < ApplicationController

  def show
    @project_phase = ProjectPhase.find(params[:id])
    @project_phase_deliverables = ProjectPhaseDeliverable.find_all_by_project_phase_id(@project_phase.id)
  end
end

app/helpers/project_phases_helper.rb
module ProjectPhasesHelper
end

app/views/project_phases/show.html.erb
<% provide(:title, "Phase Summary") %>

<h3 id="page_header"><%= @project_phase.name %> Summary</h3>

<fieldset>
  <form>

    <div class="row">
      <div class="large-12 columns">
        <label id="deliverables">Deliverables</label>
      </div>
    </div>

    <div class="row">
      <div class="large-12 columns">
        <table id="deliverable_table">
          <thead>
          <tr>
            <th>Name</th>
            <th>Type</th>
            <th>Complexity</th>
            <th>Size</th>
            <th>Unit</th>
          </tr>
          </thead>
          <tbody>
          <% @project_phase_deliverables.each_with_index do |deliverable, index| %>
              <tr id="row_<%= index + 1 %>">
                <td class="name"><%= link_to deliverable.name, deliverable %></td>
                <td class="type"><%= deliverable.deliverable_type.name %></td>
                <td class="complexity"><%= deliverable.complexity_string %></td>
                <td class="size"><%= deliverable.size %></td>
                <td class="unit"><%= deliverable.uom_string %></td>
              </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>

    <div class="row">
      <div class="large-4 large-offset-8 columns">
        <%= link_to "New Deliverable", new_project_phase_deliverable_path(project_phase_id: @project_phase.id), class: "tiny button" %>
        <!--a href="" class="tiny button" name="New Deliverable" value="New Deliverable">New Deliverable</a-->
        <a href="/projects/<%= @project_phase.project_id %>" class="tiny button" name="Back" value="Back">Back</a>
      </div>
    </div>
  </form>
</fieldset>